"""Page 5: Target Review — browse compiled target language artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
import spl3_rag_bridge as spl3_rag

# ── Constants ──────────────────────────────────────────────────────────────────

SPL30_ROOT  = spl3_rag.spl3_root()
COOKBOOK    = SPL30_ROOT / "cookbook"

CODE_EXTS   = {".go", ".py", ".swift", ".js", ".ts", ".mod"}
LANG_MODES  = {".go": "go", ".py": "python", ".swift": "swift",
               ".js": "javascript", ".ts": "typescript", ".mod": "text"}

# ── Page config ────────────────────────────────────────────────────────────────

st.set_page_config(page_title="Target Review", layout="wide")
st.header("Target Review")
st.caption(
    "Browse `.spl` scripts and their compiled target-language artifacts "
    "(Go, Python, LangGraph, etc.). Generated by `splc`."
)


# ── Discovery: find all targets/ directories ──────────────────────────────────

@st.cache_data(ttl=5)
def _discover_targets() -> list[dict]:
    """Return list of {recipe, lang, out_dir, files, has_manifest} dicts."""
    results = []
    if not COOKBOOK.exists():
        return results

    for targets_dir in sorted(COOKBOOK.rglob("targets")):
        if not targets_dir.is_dir():
            continue
        recipe_dir = targets_dir.parent
        recipe_name = recipe_dir.name

        for lang_dir in sorted(targets_dir.iterdir()):
            if not lang_dir.is_dir():
                continue
            lang_slug = lang_dir.name

            # Collect code + support files
            files = sorted([
                f for f in lang_dir.iterdir()
                if f.is_file() and f.name != "splc_manifest.json"
            ])

            manifest_file = lang_dir / "splc_manifest.json"
            manifest_data = None
            if manifest_file.exists():
                try:
                    manifest_data = json.loads(manifest_file.read_text())
                except json.JSONDecodeError:
                    pass

            results.append({
                "recipe":       recipe_name,
                "lang":         lang_slug,
                "out_dir":      lang_dir,
                "files":        files,
                "manifest":     manifest_data,
                "has_manifest": manifest_data is not None,
            })

    return results


targets = _discover_targets()

# ── Sidebar ────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.metric("Compiled targets", len(targets))

    recipe_names = sorted({t["recipe"] for t in targets})
    lang_names   = sorted({t["lang"]   for t in targets})

    st.divider()
    filter_recipe = st.selectbox(
        "Filter by recipe", ["(all)"] + recipe_names, key="filter_recipe"
    )
    filter_lang = st.selectbox(
        "Filter by language", ["(all)"] + lang_names, key="filter_lang"
    )

    st.divider()
    if st.button("Refresh", key="btn_refresh"):
        _discover_targets.clear()
        st.rerun()

    st.divider()
    st.markdown("**Navigate to SPLc**")
    st.caption("Use page 4 to compile new targets.")

# ── Filter ────────────────────────────────────────────────────────────────────

filtered = targets
if filter_recipe != "(all)":
    filtered = [t for t in filtered if t["recipe"] == filter_recipe]
if filter_lang != "(all)":
    filtered = [t for t in filtered if t["lang"] == filter_lang]

# ── Main: list + detail ───────────────────────────────────────────────────────

if not filtered:
    if not targets:
        st.info(
            "No compiled targets found yet.  \n"
            "Use **page 4 (SPLc)** to compile a `.spl` script into a target language."
        )
    else:
        st.info("No targets match the current filter.")
    st.stop()

# Build display table
table_rows = []
for t in filtered:
    code_count = sum(1 for f in t["files"] if f.suffix in CODE_EXTS)
    m = t["manifest"] or {}
    table_rows.append({
        "recipe":    t["recipe"],
        "lang":      t["lang"],
        "files":     len(t["files"]),
        "model":     m.get("model", "—"),
        "generated": (m.get("generated_at", "")[:19] if m.get("generated_at") else "—"),
        "manifest":  "yes" if t["has_manifest"] else "—",
        "_idx":      filtered.index(t),
    })

# Show selector
st.subheader(f"Compiled targets ({len(filtered)})")

for row in table_rows:
    t = filtered[row["_idx"]]
    with st.expander(
        f"**{row['recipe']}** → `{row['lang']}`  "
        f"·  {row['files']} file(s)  "
        + (f"·  {row['model']}  ·  {row['generated']}" if row["manifest"] == "yes" else ""),
        expanded=(len(filtered) == 1),
    ):
        tab_labels = ["Files"]
        if t["has_manifest"]:
            tab_labels.append("Manifest")

        tabs = st.tabs(tab_labels)
        files_tab = tabs[0]

        with files_tab:
            for f in t["files"]:
                lang_mode = LANG_MODES.get(f.suffix, "text")
                is_md = f.suffix in (".md",)
                is_code = f.suffix in CODE_EXTS

                if is_md:
                    with st.expander(f.name, expanded=(f.name.lower() in ("readme.md",))):
                        st.markdown(f.read_text())
                elif is_code:
                    with st.expander(f.name, expanded=(len(t["files"]) == 1)):
                        content = f.read_text()
                        st.code(content, language=lang_mode)
                        # LOC + size
                        loc = content.count("\n")
                        st.caption(f"{loc} lines · {len(content):,} bytes")
                else:
                    # Other support files (go.mod, requirements.txt, etc.)
                    with st.expander(f.name, expanded=False):
                        st.code(f.read_text(), language="text")

        if t["has_manifest"] and len(tabs) > 1:
            with tabs[1]:
                m = t["manifest"]
                c1, c2 = st.columns(2)
                with c1:
                    st.markdown(f"**SPL file:** `{Path(m.get('spl_file','')).name}`")
                    st.markdown(f"**Target:** `{m.get('lang','—')}`")
                    st.markdown(f"**Model:** `{m.get('model','—')}`")
                with c2:
                    st.markdown(f"**RAG:** {m.get('rag','—')} (k={m.get('rag_k','—')})")
                    st.markdown(f"**Generated:** {m.get('generated_at','—')}")
                    refs = m.get("references", [])
                    if refs:
                        st.markdown(f"**References:** {', '.join(refs)}")
                st.divider()
                st.caption("Full manifest JSON:")
                st.json(m)

        # Output directory path
        st.caption(f"Directory: `{t['out_dir']}`")
