"""
splc — deterministic SPL 3.0 → Python/LangGraph transpiler.

No LLM required.  Converts a .spl logical view to a Python/LangGraph
physical implementation using rule-based AST traversal.

Phase 1 scope (self_refine pattern):
  draft → critique → (APPROVED? commit : refine → critique)

  Handles:
    CREATE FUNCTION  → PROMPT = '''...''' constants
    WORKFLOW INPUT   → TypedDict state class + @click.option
    GENERATE INTO    → node function calling _invoke(model, PROMPT.format(...))
    CALL sub_wf INTO → inline the sub-workflow's GENERATE
    CALL write_file  → _write(path, content)
    LOGGING          → print(...)
    AssignmentStatement(@iteration := ...) → hoisted to top of node; drives return dict
    EVALUATE WHEN contains(...) THEN → _route() conditional edge
    WHILE cond DO    → graph back-edge + max-iterations guard in _route
    COMMIT           → node_commit writing final.md
"""

from __future__ import annotations

import re

from spl.ast_nodes import (
    AssignmentStatement,
    CallStatement,
    CommitStatement,
    CreateFunctionStatement,
    EvaluateStatement,
    FStringLiteral,
    GenerateIntoStatement,
    Literal,
    LoggingStatement,
    ParamRef,
    SemanticCondition,
    WhileStatement,
    WorkflowStatement,
)
from spl3.ast_nodes import CompoundCondition, NoneLiteral, UnaryOp


class LangGraphTranspiler:
    """Deterministic SPL 3.0 → Python/LangGraph transpiler.

    Usage::

        from spl.lexer import Lexer
        from spl3.parser import SPL3Parser
        from spl3.splc.transpiler_langgraph import LangGraphTranspiler

        tokens = Lexer(src).tokenize()
        program = SPL3Parser(tokens).parse()
        code = LangGraphTranspiler("self_refine").transpile(program)
    """

    def __init__(self, recipe_name: str):
        self.recipe_name = recipe_name
        self.prompts: dict[str, str] = {}          # fn_name → prompt body
        self.fn_params: dict[str, list] = {}        # fn_name → [Parameter]
        self.sub_workflows: dict[str, WorkflowStatement] = {}

    # ── Public entry point ────────────────────────────────────────────────────

    def transpile(self, program) -> str:
        """Return full Python source as a string."""
        # Pass 1: collect CREATE FUNCTION definitions
        for stmt in program.statements:
            if isinstance(stmt, CreateFunctionStatement):
                self.prompts[stmt.name] = stmt.body
                self.fn_params[stmt.name] = stmt.parameters

        # Pass 2: collect workflow definitions
        workflows = [s for s in program.statements if isinstance(s, WorkflowStatement)]
        for wf in workflows:
            self.sub_workflows[wf.name] = wf

        # Main workflow = last WorkflowStatement (the orchestrator)
        main_wf = workflows[-1]
        state_name = self._state_class_name(main_wf.name)

        parts = [
            self._gen_header(main_wf),
            self._gen_prompts(),
            self._gen_state_class(main_wf, state_name),
            self._gen_helpers(),
            self._gen_nodes(main_wf, state_name),
            self._gen_routing_function(main_wf, state_name),
            self._gen_build_graph(main_wf, state_name),
            self._gen_main(main_wf),
        ]
        return "\n\n".join(p for p in parts if p)

    # ── Code section generators ───────────────────────────────────────────────

    def _gen_header(self, wf: WorkflowStatement) -> str:
        name = wf.name
        return f'''\
"""
{name} — generated by splc (deterministic Python/LangGraph transpiler)

Pattern: draft → critique → ([APPROVED]? commit : refine → critique)

Usage:
    pip install langgraph langchain-ollama click
    python {name}_python_langgraph.py --task "Your task here"
"""

from pathlib import Path
from typing import TypedDict

import click

from langchain_ollama import ChatOllama
from langgraph.graph import END, StateGraph'''

    def _gen_prompts(self) -> str:
        lines = [
            "# ── Prompts (mirrors CREATE FUNCTION blocks in .spl) "
            "──────────────────────────"
        ]
        for name, body in self.prompts.items():
            const = name.upper() + "_PROMPT"
            body_clean = body.strip("\n")
            lines.append(f'\n{const} = """\\\n{body_clean}"""')
        return "\n".join(lines)

    def _gen_state_class(self, wf: WorkflowStatement, state_name: str) -> str:
        lines = [
            "# ── State  (SPL manages @variables implicitly) "
            "────────────────────────────────\n",
            f"class {state_name}(TypedDict):",
        ]
        for p in wf.inputs:
            pname = self._key(p.name)
            ptype = self._py_type(p.param_type)
            comment = (
                f"  # default: {self._py_default(p)}" if p.default_value else ""
            )
            lines.append(f"    {pname + ':':<22}{ptype}{comment}")

        runtime = self._collect_runtime_vars(wf)
        if runtime:
            lines.append("    # runtime variables")
            for vname, vtype in sorted(runtime.items()):
                lines.append(f"    {vname + ':':<22}{vtype}")

        return "\n".join(lines)

    def _gen_helpers(self) -> str:
        return """\
# ── Helpers ───────────────────────────────────────────────────────────────────

def _invoke(model: str, prompt: str) -> str:
    return ChatOllama(model=model).invoke(prompt).content.strip()

def _write(path: str, content: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")"""

    def _gen_nodes(self, wf: WorkflowStatement, state_name: str) -> str:
        segs = self._segment_body(wf)
        parts = [
            "# ── Nodes  (each mirrors one GENERATE / EVALUATE block) "
            "──────────────────────"
        ]
        parts.append(self._gen_node_draft(segs["init"], wf, state_name))
        parts.append(self._gen_node_critique(segs["pre_eval"], wf, state_name))
        parts.append(self._gen_node_refine(segs["else_stmts"], wf, state_name))
        parts.append(
            self._gen_node_commit(segs["when_stmts"], segs["post"], wf, state_name)
        )
        return "\n\n".join(parts)

    def _gen_node_draft(self, init_stmts, wf, state_name: str) -> str:
        gen = next((s for s in init_stmts if isinstance(s, GenerateIntoStatement)), None)
        iter_init = next(
            (
                s
                for s in init_stmts
                if isinstance(s, AssignmentStatement)
                and self._key(s.variable) == "iteration"
            ),
            None,
        )

        lines = [f"def node_draft(state: {state_name}) -> dict:"]
        if gen:
            gc = gen.generate_clause
            args_str = ", ".join(self._spl_arg(a) for a in gc.arguments)
            lines.append(
                f"    # SPL: GENERATE {gc.function_name}({args_str})"
                f" USING MODEL {gc.model}"
                f" INTO @{self._key(gen.target_variable)}"
            )

        lines.append('    print("Generating initial draft ...")')

        if gen:
            gc = gen.generate_clause
            target = self._key(gen.target_variable)
            lines.append(
                f"    {target} = _invoke({self._model_expr(gc.model)}, "
                f"{self._prompt_fmt(gc.function_name, gc.arguments)})"
            )

        # After generating, local var 'current' holds the new value
        subs = {self._key(gen.target_variable): self._key(gen.target_variable)} if gen else {}
        for s in init_stmts:
            if isinstance(s, CallStatement) and s.procedure_name == "write_file":
                args = self._write_args(s.arguments, subs)
                lines.append(f"    _write({', '.join(args)})")

        # logging after the generate
        if gen:
            gen_idx = init_stmts.index(gen)
            for s in init_stmts[gen_idx + 1 :]:
                if isinstance(s, LoggingStatement):
                    lines.append(f"    {self._log_py(s, subs)}")

        # return dict
        ret_parts = []
        if gen:
            ret_parts.append(f'"{self._key(gen.target_variable)}": {self._key(gen.target_variable)}')
        if iter_init:
            ret_parts.append(f'"iteration": {self._expr_py(iter_init.expression)}')
        lines.append(f"    return {{{', '.join(ret_parts)}}}")

        return "\n".join(lines)

    def _gen_node_critique(self, pre_eval_stmts, wf, state_name: str) -> str:
        call = next(
            (
                s
                for s in pre_eval_stmts
                if isinstance(s, CallStatement)
                and s.procedure_name in self.sub_workflows
            ),
            None,
        )

        lines = [f"def node_critique(state: {state_name}) -> dict:"]
        if call:
            args_str = ", ".join(self._spl_arg(a) for a in call.arguments)
            lines.append(
                f"    # SPL: CALL {call.procedure_name}({args_str})"
                f" INTO @{call.target_variable}"
            )

        lines.append('    i = state["iteration"]')

        # i = state["iteration"] was already emitted above
        iter_subs = {"iteration": "i"}

        # logging (use i for iteration)
        for s in pre_eval_stmts:
            if isinstance(s, LoggingStatement):
                lines.append(f"    {self._log_py(s, iter_subs)}")

        # inline the sub-workflow's GENERATE
        target = "feedback"
        if call:
            sub_wf = self.sub_workflows.get(call.procedure_name)
            if sub_wf:
                param_map = {
                    self._key(p.name): call.arguments[idx]
                    for idx, p in enumerate(sub_wf.inputs)
                    if idx < len(call.arguments)
                }
                for sub_s in sub_wf.body:
                    if isinstance(sub_s, GenerateIntoStatement):
                        gc = sub_s.generate_clause
                        model_expr = self._resolve(gc.model, param_map)
                        prompt_call = self._prompt_fmt_mapped(
                            gc.function_name, gc.arguments, param_map
                        )
                        target = (
                            self._key(call.target_variable)
                            if call.target_variable
                            else self._key(sub_s.target_variable)
                        )
                        lines.append(
                            f"    {target} = _invoke({model_expr}, {prompt_call})"
                        )
                        break

        # write_file: use local var for newly computed feedback + i for iteration
        fb_subs = {target: target, "iteration": "i"}
        for s in pre_eval_stmts:
            if isinstance(s, CallStatement) and s.procedure_name == "write_file":
                args = self._write_args(s.arguments, fb_subs)
                lines.append(f"    _write({', '.join(args)})")

        lines.append(f'    return {{"{target}": {target}}}')

        return "\n".join(lines)

    def _gen_node_refine(self, else_stmts, wf, state_name: str) -> str:
        gen = next((s for s in else_stmts if isinstance(s, GenerateIntoStatement)), None)
        iter_assign = next(
            (
                s
                for s in else_stmts
                if isinstance(s, AssignmentStatement)
                and self._key(s.variable) == "iteration"
            ),
            None,
        )

        lines = [f"def node_refine(state: {state_name}) -> dict:"]
        if gen:
            gc = gen.generate_clause
            args_str = ", ".join(self._spl_arg(a) for a in gc.arguments)
            lines.append(
                f"    # SPL: GENERATE {gc.function_name}({args_str})"
                f" USING MODEL {gc.model}"
                f" INTO @{self._key(gen.target_variable)}"
            )

        if iter_assign:
            lines.append('    i = state["iteration"] + 1')
            lines.append('    print(f"Iteration {i} | refining ...")')

        if gen:
            gc = gen.generate_clause
            target = self._key(gen.target_variable)
            lines.append(
                f"    {target} = _invoke({self._model_expr(gc.model)}, "
                f"{self._prompt_fmt(gc.function_name, gc.arguments)})"
            )

        # After GENERATE, local 'current' holds new value; i = post-increment iteration
        refine_subs = {
            (self._key(gen.target_variable) if gen else "current"): (
                self._key(gen.target_variable) if gen else "current"
            ),
            "iteration": "i",
        }

        # write_file calls
        for s in else_stmts:
            if isinstance(s, CallStatement) and s.procedure_name == "write_file":
                args = self._write_args(s.arguments, refine_subs)
                lines.append(f"    _write({', '.join(args)})")

        # logging
        for s in else_stmts:
            if isinstance(s, LoggingStatement):
                lines.append(f"    {self._log_py(s, refine_subs)}")

        target = self._key(gen.target_variable) if gen else "current"
        if iter_assign:
            lines.append(f'    return {{"{target}": {target}, "iteration": i}}')
        else:
            lines.append(f'    return {{"{target}": {target}}}')

        return "\n".join(lines)

    def _gen_node_commit(self, when_stmts, post_stmts, wf, state_name: str) -> str:
        lines = [f"def node_commit(state: {state_name}) -> dict:"]
        lines.append("    # COMMIT @current (write final.md and log status)")

        # Write final.md (deduplicate: same file written by both paths)
        all_stmts = list(when_stmts) + list(post_stmts)
        for s in all_stmts:
            if isinstance(s, CallStatement) and s.procedure_name == "write_file":
                args = self._write_args(s.arguments)
                lines.append(f"    _write({', '.join(args)})")
                break  # only emit once

        lines.append('    approved = "[APPROVED]" in state["feedback"]')
        lines.append('    status = "complete" if approved else "max_iterations"')
        lines.append("    print(f\"Committed | status={status}  iterations={state['iteration']}\")")
        lines.append("    return {}")

        return "\n".join(lines)

    def _gen_routing_function(self, wf: WorkflowStatement, state_name: str) -> str:
        eval_stmt = self._find_evaluate(wf)
        while_stmt = self._find_while(wf)

        lines = [
            "# ── Conditional edge  (mirrors EVALUATE + WHILE logic) "
            "───────────────────────\n",
            f"def _route(state: {state_name}) -> str:",
        ]

        if eval_stmt:
            expr_key = (
                self._key(eval_stmt.expression.name)
                if isinstance(eval_stmt.expression, ParamRef)
                else str(eval_stmt.expression)
            )
            for wc in eval_stmt.when_clauses:
                cond = wc.condition
                if isinstance(cond, SemanticCondition):
                    sem = cond.semantic_value
                    if sem.startswith("contains:"):
                        match_str = sem[len("contains:"):]
                        lines.append(
                            f"    # SPL: EVALUATE @{expr_key}"
                            f" WHEN contains('{match_str}') THEN COMMIT"
                        )
                        lines.append(f"    if {repr(match_str)} in state[\"{expr_key}\"]:")
                        lines.append('        return "commit"')

        # WHILE guard: if loop condition fails → also commit
        if while_stmt:
            cond = while_stmt.condition
            if hasattr(cond, "left") and hasattr(cond, "right"):
                left = cond.left
                right = cond.right
                left_key = (
                    self._key(left.name) if isinstance(left, ParamRef) else str(left)
                )
                right_key = (
                    self._key(right.name) if isinstance(right, ParamRef) else str(right)
                )
                lines.append(
                    f'    if state["{left_key}"] >= state["{right_key}"]:'
                )
                lines.append(
                    "        # SPL: LOGGING 'Max iterations reached' LEVEL WARN"
                )
                lines.append(
                    f"        print(f\"\\nMax iterations reached"
                    f" | iterations={{state['{left_key}']}}\")"
                )
                lines.append('        return "commit"')

        lines.append('    return "refine"')
        return "\n".join(lines)

    def _gen_build_graph(self, wf: WorkflowStatement, state_name: str) -> str:
        return f"""\
# ── Graph  (SPL: implicit sequential WORKFLOW layout) ─────────────────────────

def build_graph():
    g = StateGraph({state_name})
    g.add_node("draft",    node_draft)
    g.add_node("critique", node_critique)
    g.add_node("refine",   node_refine)
    g.add_node("commit",   node_commit)

    g.set_entry_point("draft")
    g.add_edge("draft",   "critique")
    g.add_conditional_edges("critique", _route, {{"commit": "commit", "refine": "refine"}})
    g.add_edge("refine",  "critique")
    g.add_edge("commit",  END)
    return g.compile()"""

    def _gen_main(self, wf: WorkflowStatement) -> str:
        lines = [
            "# ── Entry point  (SPL: built into CLI — `spl run ...`) "
            "────────────────────────\n",
            "@click.command()",
        ]

        for p in wf.inputs:
            pname = self._key(p.name)
            flag = pname.replace("_", "-")
            ptype = self._py_type(p.param_type)
            default = self._py_default(p)
            if ptype == "int":
                lines.append(
                    f'@click.option("--{flag}", default={default},'
                    f" show_default=True, type=int)"
                )
            elif p.default_value is None:
                lines.append(f'@click.option("--{flag}", required=True)')
            else:
                lines.append(
                    f'@click.option("--{flag}", default={default}, show_default=True)'
                )

        # Function signature
        sig = ", ".join(
            f"{self._key(p.name)}: {self._py_type(p.param_type)}" for p in wf.inputs
        )
        lines.append(f"def main({sig}):")

        # Build initial state dict
        lines.append("    result = build_graph().invoke({")
        for p in wf.inputs:
            k = self._key(p.name)
            lines.append(f'        "{k}": {k},')
        runtime = self._collect_runtime_vars(wf)
        for vname, vtype in sorted(runtime.items()):
            lines.append(f'        "{vname}": {"0" if vtype == "int" else repr("")},')
        lines.append("    })")
        lines.append('    print("\\n" + "=" * 60)')

        output_var = self._find_output_var(wf)
        lines.append(f'    print(result["{output_var}"])')

        lines.append("\nif __name__ == \"__main__\":")
        lines.append("    main()")

        return "\n".join(lines)

    # ── Body segmentation ─────────────────────────────────────────────────────

    def _segment_body(self, wf: WorkflowStatement) -> dict:
        """Split workflow body into: init / pre_eval / when_stmts / else_stmts / post."""
        stmts = wf.body
        init: list = []
        pre_eval: list = []
        when_stmts: list = []
        else_stmts: list = []
        post: list = []

        while_stmt = None
        found_while = False
        for s in stmts:
            if isinstance(s, WhileStatement):
                while_stmt = s
                found_while = True
            elif not found_while:
                init.append(s)
            else:
                post.append(s)

        if while_stmt is not None:
            eval_stmt = None
            for s in while_stmt.body:
                if isinstance(s, EvaluateStatement):
                    eval_stmt = s
                    break
                pre_eval.append(s)

            if eval_stmt is not None:
                for wc in eval_stmt.when_clauses:
                    when_stmts.extend(wc.statements)
                if eval_stmt.else_statements:
                    else_stmts.extend(eval_stmt.else_statements)

        return {
            "init":       init,
            "pre_eval":   pre_eval,
            "when_stmts": when_stmts,
            "else_stmts": else_stmts,
            "post":       post,
        }

    # ── AST navigation helpers ────────────────────────────────────────────────

    def _find_while(self, wf: WorkflowStatement):
        return next((s for s in wf.body if isinstance(s, WhileStatement)), None)

    def _find_evaluate(self, wf: WorkflowStatement):
        ws = self._find_while(wf)
        if ws:
            return next((s for s in ws.body if isinstance(s, EvaluateStatement)), None)
        return None

    def _find_output_var(self, wf: WorkflowStatement) -> str:
        def scan(stmts):
            for s in stmts:
                if isinstance(s, CommitStatement):
                    if isinstance(s.expression, ParamRef):
                        return self._key(s.expression.name)
                    return "current"
                if isinstance(s, WhileStatement):
                    r = scan(s.body)
                    if r:
                        return r
                if isinstance(s, EvaluateStatement):
                    for wc in s.when_clauses:
                        r = scan(wc.statements)
                        if r:
                            return r
            return None

        return scan(wf.body) or "current"

    def _collect_runtime_vars(self, wf: WorkflowStatement) -> dict[str, str]:
        """Infer runtime TypedDict fields from GENERATE targets and assignments."""
        vars: dict[str, str] = {}

        def scan(stmts):
            for s in stmts:
                if isinstance(s, GenerateIntoStatement):
                    vars[self._key(s.target_variable)] = "str"
                if isinstance(s, AssignmentStatement):
                    k = self._key(s.variable)
                    expr = s.expression
                    if isinstance(expr, Literal) and expr.literal_type == "integer":
                        vars[k] = "int"
                    elif hasattr(expr, "op"):  # BinaryOp
                        vars[k] = "int"
                    else:
                        vars[k] = "str"
                if isinstance(s, CallStatement) and s.target_variable:
                    k = self._key(s.target_variable)
                    if k not in ("none", "None", "NONE", ""):
                        vars[k] = "str"
                if isinstance(s, WhileStatement):
                    scan(s.body)
                if isinstance(s, EvaluateStatement):
                    for wc in s.when_clauses:
                        scan(wc.statements)
                    if s.else_statements:
                        scan(s.else_statements)

        scan(wf.body)

        # Remove INPUT params (already in TypedDict from inputs)
        input_keys = {self._key(p.name) for p in wf.inputs}
        for k in list(vars):
            if k in input_keys:
                del vars[k]
        # Remove None/empty keys
        vars.pop("none", None)
        vars.pop("None", None)
        vars.pop("", None)

        return vars

    # ── Expression rendering ──────────────────────────────────────────────────

    def _key(self, var_name: str) -> str:
        """'@writer_model' → 'writer_model'"""
        return var_name.lstrip("@")

    def _expr_py(self, expr) -> str:
        """Convert an SPL expression to a Python source fragment."""
        if isinstance(expr, ParamRef):
            return f'state["{self._key(expr.name)}"]'
        if isinstance(expr, str):
            if expr.startswith("@"):
                return f'state["{self._key(expr)}"]'
            return repr(expr)
        if isinstance(expr, Literal):
            if isinstance(expr.value, str):
                return repr(expr.value)
            return str(expr.value)
        if isinstance(expr, NoneLiteral):
            return "None"
        if isinstance(expr, FStringLiteral):
            return self._fstr_py(expr.template)
        if hasattr(expr, "op"):  # BinaryOp
            left = self._expr_py(expr.left)
            right = self._expr_py(expr.right)
            return f"{left} {expr.op} {right}"
        if hasattr(expr, "operator") and hasattr(expr, "left") and hasattr(expr, "right"):
            left = self._expr_py(expr.left)
            right = self._expr_py(expr.right)
            return f"{left} {expr.operator} {right}"
        if isinstance(expr, UnaryOp):
            return f"not ({self._expr_py(expr.operand)})"
        if isinstance(expr, CompoundCondition):
            left = self._expr_py(expr.left)
            right = self._expr_py(expr.right)
            op = "and" if expr.operator == "AND" else "or"
            return f"({left} {op} {right})"
        return f"# TODO: {type(expr).__name__}"

    def _fstr_py(self, template: str) -> str:
        """'{@log_dir}/draft_{@iteration}.md' → f\"{state['log_dir']}/draft_{state['iteration']}.md\""""
        result = re.sub(r"\{@(\w+)\}", r"""{state['\1']}""", template)
        result = result.replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
        return f'f"{result}"'

    def _model_expr(self, model_field) -> str:
        """generate_clause.model → Python expression for the model string."""
        if model_field is None:
            return '"llama3.2"'
        if isinstance(model_field, str):
            if model_field.startswith("@"):
                return f'state["{self._key(model_field)}"]'
            return repr(model_field)
        return self._expr_py(model_field)

    def _resolve(self, expr, param_map: dict) -> str:
        """Resolve an expression through a sub-workflow param_map, then to state."""
        if isinstance(expr, str) and expr.startswith("@"):
            k = self._key(expr)
            if k in param_map:
                return self._expr_py(param_map[k])
            return f'state["{k}"]'
        if isinstance(expr, ParamRef):
            k = self._key(expr.name)
            if k in param_map:
                return self._expr_py(param_map[k])
            return f'state["{k}"]'
        return self._expr_py(expr)

    def _prompt_fmt(self, fn_name: str, arguments: list) -> str:
        """FN_PROMPT.format(param=state["val"], ...) for a direct GENERATE call."""
        const = fn_name.upper() + "_PROMPT"
        params = self.fn_params.get(fn_name, [])
        if not params:
            parts = [self._expr_py(a) for a in arguments]
            return f"{const}.format({', '.join(parts)})"
        kv = []
        for idx, param in enumerate(params):
            val = self._expr_py(arguments[idx]) if idx < len(arguments) else '""'
            kv.append(f"{param.name}={val}")
        return f"{const}.format({', '.join(kv)})"

    def _prompt_fmt_mapped(self, fn_name: str, arguments: list, param_map: dict) -> str:
        """Like _prompt_fmt but resolve arguments through param_map (for inlined sub-wf)."""
        const = fn_name.upper() + "_PROMPT"
        params = self.fn_params.get(fn_name, [])
        if not params:
            parts = [self._resolve(a, param_map) for a in arguments]
            return f"{const}.format({', '.join(parts)})"
        kv = []
        for idx, param in enumerate(params):
            val = self._resolve(arguments[idx], param_map) if idx < len(arguments) else '""'
            kv.append(f"{param.name}={val}")
        return f"{const}.format({', '.join(kv)})"

    def _write_args(self, arguments: list, subs: dict | None = None) -> list[str]:
        """Render write_file() arguments as Python strings.

        subs: optional {state_key: local_var_name} — replaces state["x"] / state['x']
              with the local variable name for variables already computed in the node.
        """
        out = []
        for a in arguments:
            s = self._fstr_py(a.template) if isinstance(a, FStringLiteral) else self._expr_py(a)
            if subs:
                for k, v in subs.items():
                    s = s.replace(f'state["{k}"]', v).replace(f"state['{k}']", v)
            out.append(s)
        return out

    def _log_py(self, stmt: LoggingStatement, subs: dict | None = None) -> str:
        """LoggingStatement → print(...) call.

        subs: optional {state_key: local_var} substitutions (same as _write_args).
        """
        expr = stmt.expression
        if isinstance(expr, FStringLiteral):
            s = f"print({self._fstr_py(expr.template)})"
        elif isinstance(expr, Literal):
            s = f"print({repr(str(expr.value))})"
        else:
            s = f"print({self._expr_py(expr)})"
        if subs:
            for k, v in subs.items():
                s = s.replace(f'state["{k}"]', v).replace(f"state['{k}']", v)
        return s

    def _spl_arg(self, expr) -> str:
        """Render an AST expression as a terse SPL argument string (@name or value)."""
        if isinstance(expr, ParamRef):
            return f"@{self._key(expr.name)}"
        if isinstance(expr, str) and expr.startswith("@"):
            return expr
        if isinstance(expr, Literal):
            return repr(expr.value)
        return str(expr)

    # ── Type / default helpers ────────────────────────────────────────────────

    def _state_class_name(self, wf_name: str) -> str:
        return "".join(p.title() for p in wf_name.split("_")) + "State"

    def _py_type(self, param_type: str) -> str:
        t = param_type.upper()
        if t in ("INTEGER", "INT"):
            return "int"
        if t in ("FLOAT", "REAL"):
            return "float"
        if t in ("BOOL", "BOOLEAN"):
            return "bool"
        return "str"

    def _py_default(self, param) -> str:
        if param.default_value is None:
            return "None"
        return self._expr_py(param.default_value)
